import { Transaction } from "@/types/transaction"; // adjust path if needed

const transactions: Transaction[] = [
  {
    id: "#tx-001",
    user: "Olivia Rhye",
    email: "olivia@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Monthly Salary",
  },
  {
    id: "#tx-002",
    user: "Phoenix Baker",
    email: "phoenix@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Subscription Payment",
  },
  {
    id: "#tx-003",
    user: "Demi Wilkinson",
    email: "demi@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Pending",
    date: "Jan 5, 2025",
    description: "Pending Invoice",
  },
  {
    id: "#tx-004",
    user: "Candice Wu",
    email: "candice@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Refunded",
    date: "Jan 5, 2025",
    description: "Order Refund",
  },
  {
    id: "#tx-005",
    user: "Olivia Rhye",
    email: "olivia@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Bonus",
  },
  {
    id: "#tx-006",
    user: "Phoenix Baker",
    email: "phoenix@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Utility Bill",
  },
  {
    id: "#tx-007",
    user: "Demi Wilkinson",
    email: "demi@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Pending",
    date: "Jan 5, 2025",
    description: "Loan Payment",
  },
  {
    id: "#tx-008",
    user: "Candice Wu",
    email: "candice@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Refunded",
    date: "Jan 5, 2025",
    description: "Product Return",
  },
  {
    id: "#tx-001",
    user: "John Doe",
    email: "johndoe@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Monthly Salary",
  },
  {
    id: "#tx-002",
    user: "Ernest Baker",
    email: "phoenix@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Subscription Payment",
  },
  {
    id: "#tx-003",
    user: "Lovedale Johnson",
    email: "demi@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Pending",
    date: "Jan 5, 2025",
    description: "Pending Invoice",
  },
  {
    id: "#tx-004",
    user: "Declane Rice",
    email: "candice@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Refunded",
    date: "Jan 5, 2025",
    description: "Order Refund",
  },
  {
    id: "#tx-005",
    user: "Olivia Rhye",
    email: "olivia@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Bonus",
  },
  {
    id: "#tx-006",
    user: "Phoenix Baker",
    email: "phoenix@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Completed",
    date: "Jan 6, 2025",
    description: "Utility Bill",
  },
  {
    id: "#tx-007",
    user: "Demi Wilkinson",
    email: "demi@untitledui.com",
    type: "Debit",
    amount: 144.55,
    status: "Pending",
    date: "Jan 5, 2025",
    description: "Loan Payment",
  },
  {
    id: "#tx-008",
    user: "Candice Wu",
    email: "candice@untitledui.com",
    type: "Credit",
    amount: 144.55,
    status: "Refunded",
    date: "Jan 5, 2025",
    description: "Product Return",
  },
];

export default transactions;
