export const users = [
  {
    id: "1",
    name: "Savannah Nguyen",
    email: "savanna@gmail.com",
    role: "Admin",
    status: "active",
    phone: "(406) 555-0120",
    joinDate: "Jan 6, 2025",
    image: "/svg/Avatar.svg",
    walletBalance: "$144.55",
    transactions: 35,
    transactionVolume: "$191.95",
    activities: [
      {
        id: "txn-001",
        type: "Credit",
        description: "Transaction description",
        date: "Jan 6, 2025",
        amount: 144.55,
      },
      {
        id: "txn-002",
        type: "Debit",
        description: "Another transaction",
        date: "Jan 5, 2025",
        amount: 44.22,
      },
    ],
  },
  {
    id: "2",
    name: "Dianne Russell",
    email: "Diane@gmail.com",
    role: "Admin",
    status: "inactive",
    phone: "(406) 555-0120",
    joinDate: "Jan 6, 2025",
    image: "/svg/Avatar.svg",
    walletBalance: "$144.55",
    transactions: 35,
    transactionVolume: "$191.95",
    activities: [
      {
        id: "txn-001",
        type: "Credit",
        description: "Transaction description",
        date: "Jan 6, 2025",
        amount: 144.55,
      },
      {
        id: "txn-002",
        type: "Debit",
        description: "Another transaction",
        date: "Jan 5, 2025",
        amount: 44.22,
      },
    ],
  },
  {
    id: "3",
    name: "Ronald Richards",
    email: "Ronald@gmail.com",
    role: "Admin",
    status: "active",
    phone: "(406) 555-0120",
    joinDate: "Jan 6, 2025",
    image: "svg/Avatar.svg",
    walletBalance: "$144.55",
    transactions: 35,
    transactionVolume: "$191.95",
    activities: [
      {
        id: "txn-001",
        type: "Credit",
        description: "Transaction description",
        date: "Jan 6, 2025",
        amount: 144.55,
      },
      {
        id: "txn-002",
        type: "Debit",
        description: "Another transaction",
        date: "Jan 5, 2025",
        amount: 44.22,
      },
    ],
  },
];
